export interface City {
  name: string
  timezone: string // IANA timezone, e.g. "America/New_York"
}

export interface Country {
  name: string
  cities: City[]
}

export interface RegionData {
  name: string
  countries: Country[]
}

export const LOCATION_DATA: RegionData[] = [
  {
    name: "North America",
    countries: [
      {
        name: "United States",
        cities: [
          { name: "New York", timezone: "America/New_York" },
          { name: "Los Angeles", timezone: "America/Los_Angeles" },
          { name: "Chicago", timezone: "America/Chicago" },
          { name: "Houston", timezone: "America/Chicago" },
          { name: "Phoenix", timezone: "America/Phoenix" },
          { name: "Philadelphia", timezone: "America/New_York" },
          { name: "San Antonio", timezone: "America/Chicago" },
          { name: "San Diego", timezone: "America/Los_Angeles" },
          { name: "Dallas", timezone: "America/Chicago" },
          { name: "San Jose", timezone: "America/Los_Angeles" },
          { name: "Austin", timezone: "America/Chicago" },
          { name: "Jacksonville", timezone: "America/New_York" },
          { name: "San Francisco", timezone: "America/Los_Angeles" },
          { name: "Columbus", timezone: "America/New_York" },
          { name: "Charlotte", timezone: "America/New_York" },
          { name: "Indianapolis", timezone: "America/Indiana/Indianapolis" },
          { name: "Seattle", timezone: "America/Los_Angeles" },
          { name: "Denver", timezone: "America/Denver" },
          { name: "Nashville", timezone: "America/Chicago" },
          { name: "Oklahoma City", timezone: "America/Chicago" },
          { name: "El Paso", timezone: "America/Denver" },
          { name: "Washington D.C.", timezone: "America/New_York" },
          { name: "Las Vegas", timezone: "America/Los_Angeles" },
          { name: "Louisville", timezone: "America/Kentucky/Louisville" },
          { name: "Memphis", timezone: "America/Chicago" },
          { name: "Portland", timezone: "America/Los_Angeles" },
          { name: "Baltimore", timezone: "America/New_York" },
          { name: "Milwaukee", timezone: "America/Chicago" },
          { name: "Albuquerque", timezone: "America/Denver" },
          { name: "Tucson", timezone: "America/Phoenix" },
          { name: "Fresno", timezone: "America/Los_Angeles" },
          { name: "Sacramento", timezone: "America/Los_Angeles" },
          { name: "Mesa", timezone: "America/Phoenix" },
          { name: "Kansas City", timezone: "America/Chicago" },
          { name: "Atlanta", timezone: "America/New_York" },
          { name: "Omaha", timezone: "America/Chicago" },
          { name: "Colorado Springs", timezone: "America/Denver" },
          { name: "Raleigh", timezone: "America/New_York" },
          { name: "Long Beach", timezone: "America/Los_Angeles" },
          { name: "Virginia Beach", timezone: "America/New_York" },
          { name: "Minneapolis", timezone: "America/Chicago" },
          { name: "Tampa", timezone: "America/New_York" },
          { name: "New Orleans", timezone: "America/Chicago" },
          { name: "Arlington", timezone: "America/Chicago" },
          { name: "Boston", timezone: "America/New_York" },
          { name: "Cleveland", timezone: "America/New_York" },
          { name: "Pittsburgh", timezone: "America/New_York" },
          { name: "Detroit", timezone: "America/Detroit" },
          { name: "Miami", timezone: "America/New_York" },
          { name: "Salt Lake City", timezone: "America/Denver" },
          { name: "Honolulu", timezone: "Pacific/Honolulu" },
          { name: "Anchorage", timezone: "America/Anchorage" },
        ],
      },
      {
        name: "Canada",
        cities: [
          { name: "Toronto", timezone: "America/Toronto" },
          { name: "Montreal", timezone: "America/Toronto" },
          { name: "Vancouver", timezone: "America/Vancouver" },
          { name: "Calgary", timezone: "America/Edmonton" },
          { name: "Edmonton", timezone: "America/Edmonton" },
          { name: "Ottawa", timezone: "America/Toronto" },
          { name: "Winnipeg", timezone: "America/Winnipeg" },
          { name: "Quebec City", timezone: "America/Toronto" },
          { name: "Hamilton", timezone: "America/Toronto" },
          { name: "Kitchener", timezone: "America/Toronto" },
          { name: "London", timezone: "America/Toronto" },
          { name: "Halifax", timezone: "America/Halifax" },
          { name: "Oshawa", timezone: "America/Toronto" },
          { name: "Victoria", timezone: "America/Vancouver" },
          { name: "Windsor", timezone: "America/Toronto" },
          { name: "Saskatoon", timezone: "America/Regina" },
          { name: "Regina", timezone: "America/Regina" },
          { name: "Kelowna", timezone: "America/Vancouver" },
          { name: "St. John's", timezone: "America/St_Johns" },
          { name: "Moncton", timezone: "America/Moncton" },
        ],
      },
      {
        name: "Mexico",
        cities: [
          { name: "Mexico City", timezone: "America/Mexico_City" },
          { name: "Guadalajara", timezone: "America/Mexico_City" },
          { name: "Monterrey", timezone: "America/Monterrey" },
          { name: "Puebla", timezone: "America/Mexico_City" },
          { name: "Tijuana", timezone: "America/Tijuana" },
          { name: "León", timezone: "America/Mexico_City" },
          { name: "Ciudad Juárez", timezone: "America/Chihuahua" },
          { name: "Zapopan", timezone: "America/Mexico_City" },
          { name: "Mérida", timezone: "America/Merida" },
          { name: "San Luis Potosí", timezone: "America/Mexico_City" },
          { name: "Aguascalientes", timezone: "America/Mexico_City" },
          { name: "Hermosillo", timezone: "America/Hermosillo" },
          { name: "Saltillo", timezone: "America/Monterrey" },
          { name: "Mexicali", timezone: "America/Tijuana" },
          { name: "Culiacán", timezone: "America/Mazatlan" },
          { name: "Cancún", timezone: "America/Cancun" },
          { name: "Acapulco", timezone: "America/Mexico_City" },
          { name: "Morelia", timezone: "America/Mexico_City" },
          { name: "Veracruz", timezone: "America/Mexico_City" },
          { name: "Querétaro", timezone: "America/Mexico_City" },
          { name: "Oaxaca", timezone: "America/Mexico_City" },
          { name: "San Miguel de Allende", timezone: "America/Mexico_City" },
        ],
      },
    ],
  },
  {
    name: "Latin America",
    countries: [
      {
        name: "Brazil",
        cities: [
          { name: "São Paulo", timezone: "America/Sao_Paulo" },
          { name: "Rio de Janeiro", timezone: "America/Sao_Paulo" },
          { name: "Brasília", timezone: "America/Sao_Paulo" },
          { name: "Salvador", timezone: "America/Bahia" },
          { name: "Fortaleza", timezone: "America/Fortaleza" },
          { name: "Belo Horizonte", timezone: "America/Sao_Paulo" },
          { name: "Manaus", timezone: "America/Manaus" },
          { name: "Curitiba", timezone: "America/Sao_Paulo" },
          { name: "Recife", timezone: "America/Recife" },
          { name: "Porto Alegre", timezone: "America/Sao_Paulo" },
          { name: "Belém", timezone: "America/Belem" },
          { name: "Goiânia", timezone: "America/Sao_Paulo" },
          { name: "Florianópolis", timezone: "America/Sao_Paulo" },
          { name: "Campinas", timezone: "America/Sao_Paulo" },
          { name: "São Luís", timezone: "America/Fortaleza" },
          { name: "Maceió", timezone: "America/Maceio" },
          { name: "Natal", timezone: "America/Fortaleza" },
          { name: "Teresina", timezone: "America/Fortaleza" },
          { name: "Campo Grande", timezone: "America/Campo_Grande" },
          { name: "João Pessoa", timezone: "America/Fortaleza" },
          { name: "Aracaju", timezone: "America/Maceio" },
          { name: "Uberlândia", timezone: "America/Sao_Paulo" },
          { name: "Sorocaba", timezone: "America/Sao_Paulo" },
          { name: "Joinville", timezone: "America/Sao_Paulo" },
        ],
      },
      {
        name: "Argentina",
        cities: [
          { name: "Buenos Aires", timezone: "America/Argentina/Buenos_Aires" },
          { name: "Córdoba", timezone: "America/Argentina/Cordoba" },
          { name: "Rosario", timezone: "America/Argentina/Buenos_Aires" },
          { name: "Mendoza", timezone: "America/Argentina/Mendoza" },
          { name: "Tucumán", timezone: "America/Argentina/Tucuman" },
          { name: "La Plata", timezone: "America/Argentina/Buenos_Aires" },
          { name: "Mar del Plata", timezone: "America/Argentina/Buenos_Aires" },
          { name: "Salta", timezone: "America/Argentina/Salta" },
          { name: "Santa Fe", timezone: "America/Argentina/Buenos_Aires" },
          { name: "San Juan", timezone: "America/Argentina/San_Juan" },
          { name: "Resistencia", timezone: "America/Argentina/Buenos_Aires" },
          { name: "Neuquén", timezone: "America/Argentina/Salta" },
          { name: "Bahía Blanca", timezone: "America/Argentina/Buenos_Aires" },
          { name: "Bariloche", timezone: "America/Argentina/Salta" },
          { name: "Ushuaia", timezone: "America/Argentina/Ushuaia" },
        ],
      },
      {
        name: "Colombia",
        cities: [
          { name: "Bogotá", timezone: "America/Bogota" },
          { name: "Medellín", timezone: "America/Bogota" },
          { name: "Cali", timezone: "America/Bogota" },
          { name: "Barranquilla", timezone: "America/Bogota" },
          { name: "Cartagena", timezone: "America/Bogota" },
          { name: "Cúcuta", timezone: "America/Bogota" },
          { name: "Bucaramanga", timezone: "America/Bogota" },
          { name: "Pereira", timezone: "America/Bogota" },
          { name: "Manizales", timezone: "America/Bogota" },
          { name: "Santa Marta", timezone: "America/Bogota" },
          { name: "Ibagué", timezone: "America/Bogota" },
          { name: "Pasto", timezone: "America/Bogota" },
          { name: "Villavicencio", timezone: "America/Bogota" },
          { name: "Montería", timezone: "America/Bogota" },
        ],
      },
      {
        name: "Chile",
        cities: [
          { name: "Santiago", timezone: "America/Santiago" },
          { name: "Valparaíso", timezone: "America/Santiago" },
          { name: "Concepción", timezone: "America/Santiago" },
          { name: "La Serena", timezone: "America/Santiago" },
          { name: "Antofagasta", timezone: "America/Santiago" },
          { name: "Temuco", timezone: "America/Santiago" },
          { name: "Rancagua", timezone: "America/Santiago" },
          { name: "Talca", timezone: "America/Santiago" },
          { name: "Arica", timezone: "America/Santiago" },
          { name: "Puerto Montt", timezone: "America/Santiago" },
          { name: "Iquique", timezone: "America/Santiago" },
          { name: "Punta Arenas", timezone: "America/Punta_Arenas" },
        ],
      },
      {
        name: "Peru",
        cities: [
          { name: "Lima", timezone: "America/Lima" },
          { name: "Arequipa", timezone: "America/Lima" },
          { name: "Trujillo", timezone: "America/Lima" },
          { name: "Chiclayo", timezone: "America/Lima" },
          { name: "Cusco", timezone: "America/Lima" },
          { name: "Piura", timezone: "America/Lima" },
          { name: "Iquitos", timezone: "America/Lima" },
          { name: "Huancayo", timezone: "America/Lima" },
          { name: "Tacna", timezone: "America/Lima" },
          { name: "Pucallpa", timezone: "America/Lima" },
        ],
      },
      {
        name: "Venezuela",
        cities: [
          { name: "Caracas", timezone: "America/Caracas" },
          { name: "Maracaibo", timezone: "America/Caracas" },
          { name: "Valencia", timezone: "America/Caracas" },
          { name: "Barquisimeto", timezone: "America/Caracas" },
          { name: "Maracay", timezone: "America/Caracas" },
          { name: "Ciudad Guayana", timezone: "America/Caracas" },
          { name: "Mérida", timezone: "America/Caracas" },
          { name: "Barcelona", timezone: "America/Caracas" },
        ],
      },
      {
        name: "Ecuador",
        cities: [
          { name: "Guayaquil", timezone: "America/Guayaquil" },
          { name: "Quito", timezone: "America/Guayaquil" },
          { name: "Cuenca", timezone: "America/Guayaquil" },
          { name: "Santo Domingo", timezone: "America/Guayaquil" },
          { name: "Machala", timezone: "America/Guayaquil" },
          { name: "Durán", timezone: "America/Guayaquil" },
          { name: "Manta", timezone: "America/Guayaquil" },
          { name: "Loja", timezone: "America/Guayaquil" },
        ],
      },
      {
        name: "Bolivia",
        cities: [
          { name: "Santa Cruz de la Sierra", timezone: "America/La_Paz" },
          { name: "La Paz", timezone: "America/La_Paz" },
          { name: "Cochabamba", timezone: "America/La_Paz" },
          { name: "Oruro", timezone: "America/La_Paz" },
          { name: "Sucre", timezone: "America/La_Paz" },
          { name: "Potosí", timezone: "America/La_Paz" },
          { name: "Tarija", timezone: "America/La_Paz" },
        ],
      },
      {
        name: "Paraguay",
        cities: [
          { name: "Asunción", timezone: "America/Asuncion" },
          { name: "Ciudad del Este", timezone: "America/Asuncion" },
          { name: "Encarnación", timezone: "America/Asuncion" },
          { name: "San Lorenzo", timezone: "America/Asuncion" },
          { name: "Caaguazú", timezone: "America/Asuncion" },
        ],
      },
      {
        name: "Uruguay",
        cities: [
          { name: "Montevideo", timezone: "America/Montevideo" },
          { name: "Salto", timezone: "America/Montevideo" },
          { name: "Ciudad de la Costa", timezone: "America/Montevideo" },
          { name: "Paysandú", timezone: "America/Montevideo" },
          { name: "Las Piedras", timezone: "America/Montevideo" },
          { name: "Punta del Este", timezone: "America/Montevideo" },
        ],
      },
      {
        name: "Costa Rica",
        cities: [
          { name: "San José", timezone: "America/Costa_Rica" },
          { name: "Alajuela", timezone: "America/Costa_Rica" },
          { name: "Cartago", timezone: "America/Costa_Rica" },
          { name: "Heredia", timezone: "America/Costa_Rica" },
          { name: "Limón", timezone: "America/Costa_Rica" },
        ],
      },
      {
        name: "Panama",
        cities: [
          { name: "Panama City", timezone: "America/Panama" },
          { name: "San Miguelito", timezone: "America/Panama" },
          { name: "Colón", timezone: "America/Panama" },
          { name: "David", timezone: "America/Panama" },
        ],
      },
      {
        name: "Guatemala",
        cities: [
          { name: "Guatemala City", timezone: "America/Guatemala" },
          { name: "Quetzaltenango", timezone: "America/Guatemala" },
          { name: "Mixco", timezone: "America/Guatemala" },
          { name: "Villa Nueva", timezone: "America/Guatemala" },
          { name: "Cobán", timezone: "America/Guatemala" },
        ],
      },
      {
        name: "Honduras",
        cities: [
          { name: "Tegucigalpa", timezone: "America/Tegucigalpa" },
          { name: "San Pedro Sula", timezone: "America/Tegucigalpa" },
          { name: "Choloma", timezone: "America/Tegucigalpa" },
        ],
      },
      {
        name: "El Salvador",
        cities: [
          { name: "San Salvador", timezone: "America/El_Salvador" },
          { name: "Santa Ana", timezone: "America/El_Salvador" },
          { name: "San Miguel", timezone: "America/El_Salvador" },
        ],
      },
      {
        name: "Nicaragua",
        cities: [
          { name: "Managua", timezone: "America/Managua" },
          { name: "León", timezone: "America/Managua" },
          { name: "Masaya", timezone: "America/Managua" },
        ],
      },
      {
        name: "Dominican Republic",
        cities: [
          { name: "Santo Domingo", timezone: "America/Santo_Domingo" },
          { name: "Santiago de los Caballeros", timezone: "America/Santo_Domingo" },
          { name: "La Romana", timezone: "America/Santo_Domingo" },
          { name: "San Pedro de Macorís", timezone: "America/Santo_Domingo" },
        ],
      },
      {
        name: "Cuba",
        cities: [
          { name: "Havana", timezone: "America/Havana" },
          { name: "Santiago de Cuba", timezone: "America/Havana" },
          { name: "Camagüey", timezone: "America/Havana" },
          { name: "Holguín", timezone: "America/Havana" },
        ],
      },
      {
        name: "Puerto Rico",
        cities: [
          { name: "San Juan", timezone: "America/Puerto_Rico" },
          { name: "Bayamón", timezone: "America/Puerto_Rico" },
          { name: "Carolina", timezone: "America/Puerto_Rico" },
          { name: "Ponce", timezone: "America/Puerto_Rico" },
        ],
      },
    ],
  },
  {
    name: "Europe",
    countries: [
      {
        name: "United Kingdom",
        cities: [
          { name: "London", timezone: "Europe/London" },
          { name: "Birmingham", timezone: "Europe/London" },
          { name: "Manchester", timezone: "Europe/London" },
          { name: "Leeds", timezone: "Europe/London" },
          { name: "Glasgow", timezone: "Europe/London" },
          { name: "Sheffield", timezone: "Europe/London" },
          { name: "Bradford", timezone: "Europe/London" },
          { name: "Liverpool", timezone: "Europe/London" },
          { name: "Edinburgh", timezone: "Europe/London" },
          { name: "Bristol", timezone: "Europe/London" },
          { name: "Cardiff", timezone: "Europe/London" },
          { name: "Leicester", timezone: "Europe/London" },
          { name: "Coventry", timezone: "Europe/London" },
          { name: "Nottingham", timezone: "Europe/London" },
          { name: "Newcastle", timezone: "Europe/London" },
          { name: "Belfast", timezone: "Europe/London" },
          { name: "Southampton", timezone: "Europe/London" },
          { name: "Brighton", timezone: "Europe/London" },
          { name: "Oxford", timezone: "Europe/London" },
          { name: "Cambridge", timezone: "Europe/London" },
          { name: "Aberdeen", timezone: "Europe/London" },
          { name: "Dundee", timezone: "Europe/London" },
        ],
      },
      {
        name: "Germany",
        cities: [
          { name: "Berlin", timezone: "Europe/Berlin" },
          { name: "Hamburg", timezone: "Europe/Berlin" },
          { name: "Munich", timezone: "Europe/Berlin" },
          { name: "Cologne", timezone: "Europe/Berlin" },
          { name: "Frankfurt", timezone: "Europe/Berlin" },
          { name: "Stuttgart", timezone: "Europe/Berlin" },
          { name: "Düsseldorf", timezone: "Europe/Berlin" },
          { name: "Leipzig", timezone: "Europe/Berlin" },
          { name: "Dortmund", timezone: "Europe/Berlin" },
          { name: "Essen", timezone: "Europe/Berlin" },
          { name: "Bremen", timezone: "Europe/Berlin" },
          { name: "Dresden", timezone: "Europe/Berlin" },
          { name: "Hanover", timezone: "Europe/Berlin" },
          { name: "Nuremberg", timezone: "Europe/Berlin" },
          { name: "Duisburg", timezone: "Europe/Berlin" },
          { name: "Bochum", timezone: "Europe/Berlin" },
          { name: "Wuppertal", timezone: "Europe/Berlin" },
          { name: "Bielefeld", timezone: "Europe/Berlin" },
          { name: "Bonn", timezone: "Europe/Berlin" },
          { name: "Mannheim", timezone: "Europe/Berlin" },
          { name: "Karlsruhe", timezone: "Europe/Berlin" },
          { name: "Augsburg", timezone: "Europe/Berlin" },
          { name: "Münster", timezone: "Europe/Berlin" },
          { name: "Freiburg", timezone: "Europe/Berlin" },
          { name: "Kiel", timezone: "Europe/Berlin" },
          { name: "Aachen", timezone: "Europe/Berlin" },
          { name: "Mainz", timezone: "Europe/Berlin" },
        ],
      },
      {
        name: "France",
        cities: [
          { name: "Paris", timezone: "Europe/Paris" },
          { name: "Marseille", timezone: "Europe/Paris" },
          { name: "Lyon", timezone: "Europe/Paris" },
          { name: "Toulouse", timezone: "Europe/Paris" },
          { name: "Nice", timezone: "Europe/Paris" },
          { name: "Nantes", timezone: "Europe/Paris" },
          { name: "Strasbourg", timezone: "Europe/Paris" },
          { name: "Montpellier", timezone: "Europe/Paris" },
          { name: "Bordeaux", timezone: "Europe/Paris" },
          { name: "Lille", timezone: "Europe/Paris" },
          { name: "Rennes", timezone: "Europe/Paris" },
          { name: "Reims", timezone: "Europe/Paris" },
          { name: "Le Havre", timezone: "Europe/Paris" },
          { name: "Grenoble", timezone: "Europe/Paris" },
          { name: "Dijon", timezone: "Europe/Paris" },
          { name: "Angers", timezone: "Europe/Paris" },
          { name: "Nîmes", timezone: "Europe/Paris" },
          { name: "Clermont-Ferrand", timezone: "Europe/Paris" },
          { name: "Aix-en-Provence", timezone: "Europe/Paris" },
          { name: "Tours", timezone: "Europe/Paris" },
          { name: "Cannes", timezone: "Europe/Paris" },
          { name: "Brest", timezone: "Europe/Paris" },
        ],
      },
      {
        name: "Spain",
        cities: [
          { name: "Madrid", timezone: "Europe/Madrid" },
          { name: "Barcelona", timezone: "Europe/Madrid" },
          { name: "Valencia", timezone: "Europe/Madrid" },
          { name: "Seville", timezone: "Europe/Madrid" },
          { name: "Zaragoza", timezone: "Europe/Madrid" },
          { name: "Málaga", timezone: "Europe/Madrid" },
          { name: "Murcia", timezone: "Europe/Madrid" },
          { name: "Palma", timezone: "Europe/Madrid" },
          { name: "Las Palmas", timezone: "Atlantic/Canary" },
          { name: "Bilbao", timezone: "Europe/Madrid" },
          { name: "Alicante", timezone: "Europe/Madrid" },
          { name: "Córdoba", timezone: "Europe/Madrid" },
          { name: "Valladolid", timezone: "Europe/Madrid" },
          { name: "Vigo", timezone: "Europe/Madrid" },
          { name: "Gijón", timezone: "Europe/Madrid" },
          { name: "Granada", timezone: "Europe/Madrid" },
          { name: "Vitoria-Gasteiz", timezone: "Europe/Madrid" },
          { name: "La Coruña", timezone: "Europe/Madrid" },
          { name: "Santa Cruz de Tenerife", timezone: "Atlantic/Canary" },
          { name: "San Sebastián", timezone: "Europe/Madrid" },
          { name: "Pamplona", timezone: "Europe/Madrid" },
          { name: "Santander", timezone: "Europe/Madrid" },
        ],
      },
      {
        name: "Italy",
        cities: [
          { name: "Rome", timezone: "Europe/Rome" },
          { name: "Milan", timezone: "Europe/Rome" },
          { name: "Naples", timezone: "Europe/Rome" },
          { name: "Turin", timezone: "Europe/Rome" },
          { name: "Palermo", timezone: "Europe/Rome" },
          { name: "Genoa", timezone: "Europe/Rome" },
          { name: "Bologna", timezone: "Europe/Rome" },
          { name: "Florence", timezone: "Europe/Rome" },
          { name: "Bari", timezone: "Europe/Rome" },
          { name: "Catania", timezone: "Europe/Rome" },
          { name: "Venice", timezone: "Europe/Rome" },
          { name: "Verona", timezone: "Europe/Rome" },
          { name: "Messina", timezone: "Europe/Rome" },
          { name: "Padua", timezone: "Europe/Rome" },
          { name: "Trieste", timezone: "Europe/Rome" },
          { name: "Brescia", timezone: "Europe/Rome" },
          { name: "Taranto", timezone: "Europe/Rome" },
          { name: "Modena", timezone: "Europe/Rome" },
          { name: "Reggio Calabria", timezone: "Europe/Rome" },
          { name: "Pisa", timezone: "Europe/Rome" },
          { name: "Siena", timezone: "Europe/Rome" },
        ],
      },
      {
        name: "Netherlands",
        cities: [
          { name: "Amsterdam", timezone: "Europe/Amsterdam" },
          { name: "Rotterdam", timezone: "Europe/Amsterdam" },
          { name: "The Hague", timezone: "Europe/Amsterdam" },
          { name: "Utrecht", timezone: "Europe/Amsterdam" },
          { name: "Eindhoven", timezone: "Europe/Amsterdam" },
          { name: "Tilburg", timezone: "Europe/Amsterdam" },
          { name: "Groningen", timezone: "Europe/Amsterdam" },
          { name: "Almere", timezone: "Europe/Amsterdam" },
          { name: "Breda", timezone: "Europe/Amsterdam" },
          { name: "Nijmegen", timezone: "Europe/Amsterdam" },
          { name: "Leiden", timezone: "Europe/Amsterdam" },
          { name: "Maastricht", timezone: "Europe/Amsterdam" },
        ],
      },
      {
        name: "Portugal",
        cities: [
          { name: "Lisbon", timezone: "Europe/Lisbon" },
          { name: "Porto", timezone: "Europe/Lisbon" },
          { name: "Amadora", timezone: "Europe/Lisbon" },
          { name: "Braga", timezone: "Europe/Lisbon" },
          { name: "Setúbal", timezone: "Europe/Lisbon" },
          { name: "Coimbra", timezone: "Europe/Lisbon" },
          { name: "Almada", timezone: "Europe/Lisbon" },
          { name: "Aveiro", timezone: "Europe/Lisbon" },
          { name: "Évora", timezone: "Europe/Lisbon" },
          { name: "Faro", timezone: "Europe/Lisbon" },
          { name: "Funchal", timezone: "Atlantic/Madeira" },
          { name: "Ponta Delgada", timezone: "Atlantic/Azores" },
        ],
      },
      {
        name: "Switzerland",
        cities: [
          { name: "Zurich", timezone: "Europe/Zurich" },
          { name: "Geneva", timezone: "Europe/Zurich" },
          { name: "Basel", timezone: "Europe/Zurich" },
          { name: "Bern", timezone: "Europe/Zurich" },
          { name: "Lausanne", timezone: "Europe/Zurich" },
          { name: "Winterthur", timezone: "Europe/Zurich" },
          { name: "Lucerne", timezone: "Europe/Zurich" },
          { name: "St. Gallen", timezone: "Europe/Zurich" },
          { name: "Lugano", timezone: "Europe/Zurich" },
          { name: "Zug", timezone: "Europe/Zurich" },
        ],
      },
      {
        name: "Poland",
        cities: [
          { name: "Warsaw", timezone: "Europe/Warsaw" },
          { name: "Kraków", timezone: "Europe/Warsaw" },
          { name: "Łódź", timezone: "Europe/Warsaw" },
          { name: "Wrocław", timezone: "Europe/Warsaw" },
          { name: "Poznań", timezone: "Europe/Warsaw" },
          { name: "Gdańsk", timezone: "Europe/Warsaw" },
          { name: "Szczecin", timezone: "Europe/Warsaw" },
          { name: "Bydgoszcz", timezone: "Europe/Warsaw" },
          { name: "Lublin", timezone: "Europe/Warsaw" },
          { name: "Katowice", timezone: "Europe/Warsaw" },
          { name: "Białystok", timezone: "Europe/Warsaw" },
          { name: "Rzeszów", timezone: "Europe/Warsaw" },
          { name: "Gdynia", timezone: "Europe/Warsaw" },
          { name: "Toruń", timezone: "Europe/Warsaw" },
        ],
      },
      {
        name: "Ukraine",
        cities: [
          { name: "Kyiv", timezone: "Europe/Kiev" },
          { name: "Kharkiv", timezone: "Europe/Kiev" },
          { name: "Odesa", timezone: "Europe/Kiev" },
          { name: "Dnipro", timezone: "Europe/Kiev" },
          { name: "Donetsk", timezone: "Europe/Kiev" },
          { name: "Zaporizhzhia", timezone: "Europe/Kiev" },
          { name: "Lviv", timezone: "Europe/Kiev" },
          { name: "Kryvyi Rih", timezone: "Europe/Kiev" },
          { name: "Mykolaiv", timezone: "Europe/Kiev" },
          { name: "Mariupol", timezone: "Europe/Kiev" },
          { name: "Chernivtsi", timezone: "Europe/Kiev" },
          { name: "Vinnytsia", timezone: "Europe/Kiev" },
        ],
      },
      {
        name: "Sweden",
        cities: [
          { name: "Stockholm", timezone: "Europe/Stockholm" },
          { name: "Gothenburg", timezone: "Europe/Stockholm" },
          { name: "Malmö", timezone: "Europe/Stockholm" },
          { name: "Uppsala", timezone: "Europe/Stockholm" },
          { name: "Västerås", timezone: "Europe/Stockholm" },
          { name: "Örebro", timezone: "Europe/Stockholm" },
          { name: "Linköping", timezone: "Europe/Stockholm" },
          { name: "Helsingborg", timezone: "Europe/Stockholm" },
          { name: "Jönköping", timezone: "Europe/Stockholm" },
          { name: "Norrköping", timezone: "Europe/Stockholm" },
          { name: "Lund", timezone: "Europe/Stockholm" },
          { name: "Umeå", timezone: "Europe/Stockholm" },
        ],
      },
      {
        name: "Norway",
        cities: [
          { name: "Oslo", timezone: "Europe/Oslo" },
          { name: "Bergen", timezone: "Europe/Oslo" },
          { name: "Trondheim", timezone: "Europe/Oslo" },
          { name: "Stavanger", timezone: "Europe/Oslo" },
          { name: "Drammen", timezone: "Europe/Oslo" },
          { name: "Fredrikstad", timezone: "Europe/Oslo" },
          { name: "Kristiansand", timezone: "Europe/Oslo" },
          { name: "Tromsø", timezone: "Europe/Oslo" },
        ],
      },
      {
        name: "Denmark",
        cities: [
          { name: "Copenhagen", timezone: "Europe/Copenhagen" },
          { name: "Aarhus", timezone: "Europe/Copenhagen" },
          { name: "Odense", timezone: "Europe/Copenhagen" },
          { name: "Aalborg", timezone: "Europe/Copenhagen" },
          { name: "Frederiksberg", timezone: "Europe/Copenhagen" },
          { name: "Esbjerg", timezone: "Europe/Copenhagen" },
          { name: "Randers", timezone: "Europe/Copenhagen" },
        ],
      },
      {
        name: "Finland",
        cities: [
          { name: "Helsinki", timezone: "Europe/Helsinki" },
          { name: "Espoo", timezone: "Europe/Helsinki" },
          { name: "Tampere", timezone: "Europe/Helsinki" },
          { name: "Vantaa", timezone: "Europe/Helsinki" },
          { name: "Oulu", timezone: "Europe/Helsinki" },
          { name: "Turku", timezone: "Europe/Helsinki" },
          { name: "Jyväskylä", timezone: "Europe/Helsinki" },
          { name: "Lahti", timezone: "Europe/Helsinki" },
        ],
      },
      {
        name: "Belgium",
        cities: [
          { name: "Brussels", timezone: "Europe/Brussels" },
          { name: "Antwerp", timezone: "Europe/Brussels" },
          { name: "Ghent", timezone: "Europe/Brussels" },
          { name: "Charleroi", timezone: "Europe/Brussels" },
          { name: "Liège", timezone: "Europe/Brussels" },
          { name: "Bruges", timezone: "Europe/Brussels" },
          { name: "Namur", timezone: "Europe/Brussels" },
          { name: "Leuven", timezone: "Europe/Brussels" },
        ],
      },
      {
        name: "Austria",
        cities: [
          { name: "Vienna", timezone: "Europe/Vienna" },
          { name: "Graz", timezone: "Europe/Vienna" },
          { name: "Linz", timezone: "Europe/Vienna" },
          { name: "Salzburg", timezone: "Europe/Vienna" },
          { name: "Innsbruck", timezone: "Europe/Vienna" },
          { name: "Klagenfurt", timezone: "Europe/Vienna" },
          { name: "Villach", timezone: "Europe/Vienna" },
          { name: "Wels", timezone: "Europe/Vienna" },
          { name: "Sankt Pölten", timezone: "Europe/Vienna" },
        ],
      },
      {
        name: "Czech Republic",
        cities: [
          { name: "Prague", timezone: "Europe/Prague" },
          { name: "Brno", timezone: "Europe/Prague" },
          { name: "Ostrava", timezone: "Europe/Prague" },
          { name: "Plzeň", timezone: "Europe/Prague" },
          { name: "Liberec", timezone: "Europe/Prague" },
          { name: "Olomouc", timezone: "Europe/Prague" },
          { name: "České Budějovice", timezone: "Europe/Prague" },
          { name: "Hradec Králové", timezone: "Europe/Prague" },
        ],
      },
      {
        name: "Romania",
        cities: [
          { name: "Bucharest", timezone: "Europe/Bucharest" },
          { name: "Cluj-Napoca", timezone: "Europe/Bucharest" },
          { name: "Timișoara", timezone: "Europe/Bucharest" },
          { name: "Iași", timezone: "Europe/Bucharest" },
          { name: "Constanța", timezone: "Europe/Bucharest" },
          { name: "Craiova", timezone: "Europe/Bucharest" },
          { name: "Brașov", timezone: "Europe/Bucharest" },
          { name: "Galați", timezone: "Europe/Bucharest" },
          { name: "Ploiești", timezone: "Europe/Bucharest" },
          { name: "Oradea", timezone: "Europe/Bucharest" },
          { name: "Sibiu", timezone: "Europe/Bucharest" },
        ],
      },
      {
        name: "Hungary",
        cities: [
          { name: "Budapest", timezone: "Europe/Budapest" },
          { name: "Debrecen", timezone: "Europe/Budapest" },
          { name: "Miskolc", timezone: "Europe/Budapest" },
          { name: "Szeged", timezone: "Europe/Budapest" },
          { name: "Pécs", timezone: "Europe/Budapest" },
          { name: "Győr", timezone: "Europe/Budapest" },
          { name: "Nyíregyháza", timezone: "Europe/Budapest" },
          { name: "Kecskemét", timezone: "Europe/Budapest" },
        ],
      },
      {
        name: "Greece",
        cities: [
          { name: "Athens", timezone: "Europe/Athens" },
          { name: "Thessaloniki", timezone: "Europe/Athens" },
          { name: "Patras", timezone: "Europe/Athens" },
          { name: "Heraklion", timezone: "Europe/Athens" },
          { name: "Larissa", timezone: "Europe/Athens" },
          { name: "Volos", timezone: "Europe/Athens" },
          { name: "Rhodes", timezone: "Europe/Athens" },
          { name: "Ioannina", timezone: "Europe/Athens" },
        ],
      },
      {
        name: "Ireland",
        cities: [
          { name: "Dublin", timezone: "Europe/Dublin" },
          { name: "Cork", timezone: "Europe/Dublin" },
          { name: "Limerick", timezone: "Europe/Dublin" },
          { name: "Galway", timezone: "Europe/Dublin" },
          { name: "Waterford", timezone: "Europe/Dublin" },
          { name: "Drogheda", timezone: "Europe/Dublin" },
        ],
      },
      {
        name: "Russia",
        cities: [
          { name: "Moscow", timezone: "Europe/Moscow" },
          { name: "Saint Petersburg", timezone: "Europe/Moscow" },
          { name: "Novosibirsk", timezone: "Asia/Novosibirsk" },
          { name: "Yekaterinburg", timezone: "Asia/Yekaterinburg" },
          { name: "Nizhny Novgorod", timezone: "Europe/Moscow" },
          { name: "Kazan", timezone: "Europe/Moscow" },
          { name: "Chelyabinsk", timezone: "Asia/Yekaterinburg" },
          { name: "Omsk", timezone: "Asia/Omsk" },
          { name: "Samara", timezone: "Europe/Samara" },
          { name: "Rostov-on-Don", timezone: "Europe/Moscow" },
          { name: "Ufa", timezone: "Asia/Yekaterinburg" },
          { name: "Krasnoyarsk", timezone: "Asia/Krasnoyarsk" },
          { name: "Vladivostok", timezone: "Asia/Vladivostok" },
          { name: "Kaliningrad", timezone: "Europe/Kaliningrad" },
          { name: "Sochi", timezone: "Europe/Moscow" },
        ],
      },
      {
        name: "Serbia",
        cities: [
          { name: "Belgrade", timezone: "Europe/Belgrade" },
          { name: "Novi Sad", timezone: "Europe/Belgrade" },
          { name: "Niš", timezone: "Europe/Belgrade" },
          { name: "Kragujevac", timezone: "Europe/Belgrade" },
        ],
      },
      {
        name: "Croatia",
        cities: [
          { name: "Zagreb", timezone: "Europe/Zagreb" },
          { name: "Split", timezone: "Europe/Zagreb" },
          { name: "Rijeka", timezone: "Europe/Zagreb" },
          { name: "Osijek", timezone: "Europe/Zagreb" },
          { name: "Zadar", timezone: "Europe/Zagreb" },
          { name: "Dubrovnik", timezone: "Europe/Zagreb" },
        ],
      },
      {
        name: "Slovakia",
        cities: [
          { name: "Bratislava", timezone: "Europe/Bratislava" },
          { name: "Košice", timezone: "Europe/Bratislava" },
          { name: "Prešov", timezone: "Europe/Bratislava" },
          { name: "Žilina", timezone: "Europe/Bratislava" },
          { name: "Banská Bystrica", timezone: "Europe/Bratislava" },
        ],
      },
      {
        name: "Estonia",
        cities: [
          { name: "Tallinn", timezone: "Europe/Tallinn" },
          { name: "Tartu", timezone: "Europe/Tallinn" },
          { name: "Narva", timezone: "Europe/Tallinn" },
          { name: "Pärnu", timezone: "Europe/Tallinn" },
        ],
      },
      {
        name: "Latvia",
        cities: [
          { name: "Riga", timezone: "Europe/Riga" },
          { name: "Daugavpils", timezone: "Europe/Riga" },
          { name: "Liepāja", timezone: "Europe/Riga" },
          { name: "Jūrmala", timezone: "Europe/Riga" },
        ],
      },
      {
        name: "Lithuania",
        cities: [
          { name: "Vilnius", timezone: "Europe/Vilnius" },
          { name: "Kaunas", timezone: "Europe/Vilnius" },
          { name: "Klaipėda", timezone: "Europe/Vilnius" },
          { name: "Šiauliai", timezone: "Europe/Vilnius" },
          { name: "Panevėžys", timezone: "Europe/Vilnius" },
        ],
      },
      {
        name: "Bulgaria",
        cities: [
          { name: "Sofia", timezone: "Europe/Sofia" },
          { name: "Plovdiv", timezone: "Europe/Sofia" },
          { name: "Varna", timezone: "Europe/Sofia" },
          { name: "Burgas", timezone: "Europe/Sofia" },
          { name: "Ruse", timezone: "Europe/Sofia" },
          { name: "Stara Zagora", timezone: "Europe/Sofia" },
        ],
      },
      {
        name: "Luxembourg",
        cities: [
          { name: "Luxembourg City", timezone: "Europe/Luxembourg" },
          { name: "Esch-sur-Alzette", timezone: "Europe/Luxembourg" },
        ],
      },
      {
        name: "Malta",
        cities: [
          { name: "Valletta", timezone: "Europe/Malta" },
          { name: "Sliema", timezone: "Europe/Malta" },
          { name: "Birkirkara", timezone: "Europe/Malta" },
          { name: "St. Julian's", timezone: "Europe/Malta" },
        ],
      },
      {
        name: "Iceland",
        cities: [
          { name: "Reykjavik", timezone: "Atlantic/Reykjavik" },
          { name: "Akureyri", timezone: "Atlantic/Reykjavik" },
        ],
      },
      {
        name: "Slovenia",
        cities: [
          { name: "Ljubljana", timezone: "Europe/Ljubljana" },
          { name: "Maribor", timezone: "Europe/Ljubljana" },
          { name: "Celje", timezone: "Europe/Ljubljana" },
        ],
      },
      {
        name: "Bosnia and Herzegovina",
        cities: [
          { name: "Sarajevo", timezone: "Europe/Sarajevo" },
          { name: "Banja Luka", timezone: "Europe/Sarajevo" },
          { name: "Mostar", timezone: "Europe/Sarajevo" },
        ],
      },
      {
        name: "North Macedonia",
        cities: [
          { name: "Skopje", timezone: "Europe/Skopje" },
          { name: "Bitola", timezone: "Europe/Skopje" },
        ],
      },
      {
        name: "Albania",
        cities: [
          { name: "Tirana", timezone: "Europe/Tirane" },
          { name: "Durrës", timezone: "Europe/Tirane" },
          { name: "Vlorë", timezone: "Europe/Tirane" },
        ],
      },
      {
        name: "Moldova",
        cities: [
          { name: "Chișinău", timezone: "Europe/Chisinau" },
          { name: "Bălți", timezone: "Europe/Chisinau" },
        ],
      },
      {
        name: "Belarus",
        cities: [
          { name: "Minsk", timezone: "Europe/Minsk" },
          { name: "Gomel", timezone: "Europe/Minsk" },
          { name: "Vitebsk", timezone: "Europe/Minsk" },
          { name: "Grodno", timezone: "Europe/Minsk" },
        ],
      },
      {
        name: "Georgia",
        cities: [
          { name: "Tbilisi", timezone: "Asia/Tbilisi" },
          { name: "Batumi", timezone: "Asia/Tbilisi" },
          { name: "Kutaisi", timezone: "Asia/Tbilisi" },
        ],
      },
      {
        name: "Armenia",
        cities: [
          { name: "Yerevan", timezone: "Asia/Yerevan" },
          { name: "Gyumri", timezone: "Asia/Yerevan" },
        ],
      },
      {
        name: "Azerbaijan",
        cities: [
          { name: "Baku", timezone: "Asia/Baku" },
          { name: "Ganja", timezone: "Asia/Baku" },
        ],
      },
      {
        name: "Kazakhstan",
        cities: [
          { name: "Almaty", timezone: "Asia/Almaty" },
          { name: "Astana", timezone: "Asia/Almaty" },
          { name: "Shymkent", timezone: "Asia/Almaty" },
        ],
      },
    ],
  },
  {
    name: "Asia Pacific",
    countries: [
      {
        name: "Japan",
        cities: [
          { name: "Tokyo", timezone: "Asia/Tokyo" },
          { name: "Yokohama", timezone: "Asia/Tokyo" },
          { name: "Osaka", timezone: "Asia/Tokyo" },
          { name: "Nagoya", timezone: "Asia/Tokyo" },
          { name: "Sapporo", timezone: "Asia/Tokyo" },
          { name: "Fukuoka", timezone: "Asia/Tokyo" },
          { name: "Kobe", timezone: "Asia/Tokyo" },
          { name: "Kyoto", timezone: "Asia/Tokyo" },
          { name: "Kawasaki", timezone: "Asia/Tokyo" },
          { name: "Saitama", timezone: "Asia/Tokyo" },
          { name: "Hiroshima", timezone: "Asia/Tokyo" },
          { name: "Sendai", timezone: "Asia/Tokyo" },
          { name: "Kitakyushu", timezone: "Asia/Tokyo" },
          { name: "Chiba", timezone: "Asia/Tokyo" },
          { name: "Sakai", timezone: "Asia/Tokyo" },
          { name: "Kumamoto", timezone: "Asia/Tokyo" },
          { name: "Okayama", timezone: "Asia/Tokyo" },
          { name: "Kagoshima", timezone: "Asia/Tokyo" },
          { name: "Nara", timezone: "Asia/Tokyo" },
        ],
      },
      {
        name: "South Korea",
        cities: [
          { name: "Seoul", timezone: "Asia/Seoul" },
          { name: "Busan", timezone: "Asia/Seoul" },
          { name: "Incheon", timezone: "Asia/Seoul" },
          { name: "Daegu", timezone: "Asia/Seoul" },
          { name: "Daejeon", timezone: "Asia/Seoul" },
          { name: "Gwangju", timezone: "Asia/Seoul" },
          { name: "Suwon", timezone: "Asia/Seoul" },
          { name: "Ulsan", timezone: "Asia/Seoul" },
          { name: "Changwon", timezone: "Asia/Seoul" },
          { name: "Seongnam", timezone: "Asia/Seoul" },
          { name: "Goyang", timezone: "Asia/Seoul" },
          { name: "Jeju City", timezone: "Asia/Seoul" },
        ],
      },
      {
        name: "China",
        cities: [
          { name: "Shanghai", timezone: "Asia/Shanghai" },
          { name: "Beijing", timezone: "Asia/Shanghai" },
          { name: "Chongqing", timezone: "Asia/Shanghai" },
          { name: "Guangzhou", timezone: "Asia/Shanghai" },
          { name: "Shenzhen", timezone: "Asia/Shanghai" },
          { name: "Tianjin", timezone: "Asia/Shanghai" },
          { name: "Chengdu", timezone: "Asia/Shanghai" },
          { name: "Nanjing", timezone: "Asia/Shanghai" },
          { name: "Wuhan", timezone: "Asia/Shanghai" },
          { name: "Xi'an", timezone: "Asia/Shanghai" },
          { name: "Hangzhou", timezone: "Asia/Shanghai" },
          { name: "Shenyang", timezone: "Asia/Shanghai" },
          { name: "Harbin", timezone: "Asia/Shanghai" },
          { name: "Qingdao", timezone: "Asia/Shanghai" },
          { name: "Jinan", timezone: "Asia/Shanghai" },
          { name: "Dalian", timezone: "Asia/Shanghai" },
          { name: "Zhengzhou", timezone: "Asia/Shanghai" },
          { name: "Changsha", timezone: "Asia/Shanghai" },
          { name: "Kunming", timezone: "Asia/Shanghai" },
          { name: "Suzhou", timezone: "Asia/Shanghai" },
          { name: "Foshan", timezone: "Asia/Shanghai" },
          { name: "Dongguan", timezone: "Asia/Shanghai" },
          { name: "Nanning", timezone: "Asia/Shanghai" },
          { name: "Xiamen", timezone: "Asia/Shanghai" },
          { name: "Guiyang", timezone: "Asia/Shanghai" },
          { name: "Urumqi", timezone: "Asia/Urumqi" },
          { name: "Lhasa", timezone: "Asia/Urumqi" },
        ],
      },
      {
        name: "Singapore",
        cities: [
          { name: "Singapore", timezone: "Asia/Singapore" },
        ],
      },
      {
        name: "India",
        cities: [
          { name: "Mumbai", timezone: "Asia/Kolkata" },
          { name: "Delhi", timezone: "Asia/Kolkata" },
          { name: "Bangalore", timezone: "Asia/Kolkata" },
          { name: "Hyderabad", timezone: "Asia/Kolkata" },
          { name: "Ahmedabad", timezone: "Asia/Kolkata" },
          { name: "Chennai", timezone: "Asia/Kolkata" },
          { name: "Kolkata", timezone: "Asia/Kolkata" },
          { name: "Surat", timezone: "Asia/Kolkata" },
          { name: "Pune", timezone: "Asia/Kolkata" },
          { name: "Jaipur", timezone: "Asia/Kolkata" },
          { name: "Lucknow", timezone: "Asia/Kolkata" },
          { name: "Kanpur", timezone: "Asia/Kolkata" },
          { name: "Nagpur", timezone: "Asia/Kolkata" },
          { name: "Patna", timezone: "Asia/Kolkata" },
          { name: "Indore", timezone: "Asia/Kolkata" },
          { name: "Thane", timezone: "Asia/Kolkata" },
          { name: "Bhopal", timezone: "Asia/Kolkata" },
          { name: "Visakhapatnam", timezone: "Asia/Kolkata" },
          { name: "Pimpri-Chinchwad", timezone: "Asia/Kolkata" },
          { name: "Vadodara", timezone: "Asia/Kolkata" },
          { name: "Gurugram", timezone: "Asia/Kolkata" },
          { name: "Noida", timezone: "Asia/Kolkata" },
          { name: "Coimbatore", timezone: "Asia/Kolkata" },
          { name: "Kochi", timezone: "Asia/Kolkata" },
          { name: "Chandigarh", timezone: "Asia/Kolkata" },
          { name: "Guwahati", timezone: "Asia/Kolkata" },
          { name: "Thiruvananthapuram", timezone: "Asia/Kolkata" },
          { name: "Mangalore", timezone: "Asia/Kolkata" },
          { name: "Mysore", timezone: "Asia/Kolkata" },
          { name: "Agra", timezone: "Asia/Kolkata" },
          { name: "Varanasi", timezone: "Asia/Kolkata" },
          { name: "Amritsar", timezone: "Asia/Kolkata" },
          { name: "Dehradun", timezone: "Asia/Kolkata" },
        ],
      },
      {
        name: "Australia",
        cities: [
          { name: "Sydney", timezone: "Australia/Sydney" },
          { name: "Melbourne", timezone: "Australia/Melbourne" },
          { name: "Brisbane", timezone: "Australia/Brisbane" },
          { name: "Perth", timezone: "Australia/Perth" },
          { name: "Adelaide", timezone: "Australia/Adelaide" },
          { name: "Gold Coast", timezone: "Australia/Brisbane" },
          { name: "Newcastle", timezone: "Australia/Sydney" },
          { name: "Canberra", timezone: "Australia/Sydney" },
          { name: "Sunshine Coast", timezone: "Australia/Brisbane" },
          { name: "Wollongong", timezone: "Australia/Sydney" },
          { name: "Geelong", timezone: "Australia/Melbourne" },
          { name: "Hobart", timezone: "Australia/Hobart" },
          { name: "Townsville", timezone: "Australia/Brisbane" },
          { name: "Cairns", timezone: "Australia/Brisbane" },
          { name: "Darwin", timezone: "Australia/Darwin" },
        ],
      },
      {
        name: "New Zealand",
        cities: [
          { name: "Auckland", timezone: "Pacific/Auckland" },
          { name: "Wellington", timezone: "Pacific/Auckland" },
          { name: "Christchurch", timezone: "Pacific/Auckland" },
          { name: "Hamilton", timezone: "Pacific/Auckland" },
          { name: "Tauranga", timezone: "Pacific/Auckland" },
          { name: "Dunedin", timezone: "Pacific/Auckland" },
          { name: "Palmerston North", timezone: "Pacific/Auckland" },
          { name: "Queenstown", timezone: "Pacific/Auckland" },
        ],
      },
      {
        name: "Indonesia",
        cities: [
          { name: "Jakarta", timezone: "Asia/Jakarta" },
          { name: "Surabaya", timezone: "Asia/Jakarta" },
          { name: "Bandung", timezone: "Asia/Jakarta" },
          { name: "Medan", timezone: "Asia/Jakarta" },
          { name: "Bekasi", timezone: "Asia/Jakarta" },
          { name: "Depok", timezone: "Asia/Jakarta" },
          { name: "Tangerang", timezone: "Asia/Jakarta" },
          { name: "Semarang", timezone: "Asia/Jakarta" },
          { name: "Makassar", timezone: "Asia/Makassar" },
          { name: "Palembang", timezone: "Asia/Jakarta" },
          { name: "Yogyakarta", timezone: "Asia/Jakarta" },
          { name: "Bali (Denpasar)", timezone: "Asia/Makassar" },
          { name: "Malang", timezone: "Asia/Jakarta" },
          { name: "Pontianak", timezone: "Asia/Pontianak" },
          { name: "Balikpapan", timezone: "Asia/Makassar" },
          { name: "Manado", timezone: "Asia/Makassar" },
        ],
      },
      {
        name: "Vietnam",
        cities: [
          { name: "Ho Chi Minh City", timezone: "Asia/Ho_Chi_Minh" },
          { name: "Hanoi", timezone: "Asia/Ho_Chi_Minh" },
          { name: "Da Nang", timezone: "Asia/Ho_Chi_Minh" },
          { name: "Hai Phong", timezone: "Asia/Ho_Chi_Minh" },
          { name: "Can Tho", timezone: "Asia/Ho_Chi_Minh" },
          { name: "Bien Hoa", timezone: "Asia/Ho_Chi_Minh" },
          { name: "Hue", timezone: "Asia/Ho_Chi_Minh" },
          { name: "Nha Trang", timezone: "Asia/Ho_Chi_Minh" },
          { name: "Vung Tau", timezone: "Asia/Ho_Chi_Minh" },
          { name: "Quy Nhon", timezone: "Asia/Ho_Chi_Minh" },
        ],
      },
      {
        name: "Thailand",
        cities: [
          { name: "Bangkok", timezone: "Asia/Bangkok" },
          { name: "Nonthaburi", timezone: "Asia/Bangkok" },
          { name: "Nakhon Ratchasima", timezone: "Asia/Bangkok" },
          { name: "Chiang Mai", timezone: "Asia/Bangkok" },
          { name: "Hat Yai", timezone: "Asia/Bangkok" },
          { name: "Udon Thani", timezone: "Asia/Bangkok" },
          { name: "Pak Kret", timezone: "Asia/Bangkok" },
          { name: "Surat Thani", timezone: "Asia/Bangkok" },
          { name: "Pattaya", timezone: "Asia/Bangkok" },
          { name: "Phuket", timezone: "Asia/Bangkok" },
          { name: "Khon Kaen", timezone: "Asia/Bangkok" },
        ],
      },
      {
        name: "Philippines",
        cities: [
          { name: "Manila", timezone: "Asia/Manila" },
          { name: "Quezon City", timezone: "Asia/Manila" },
          { name: "Caloocan", timezone: "Asia/Manila" },
          { name: "Davao", timezone: "Asia/Manila" },
          { name: "Cebu", timezone: "Asia/Manila" },
          { name: "Zamboanga", timezone: "Asia/Manila" },
          { name: "Antipolo", timezone: "Asia/Manila" },
          { name: "Pasig", timezone: "Asia/Manila" },
          { name: "Cagayan de Oro", timezone: "Asia/Manila" },
          { name: "Taguig", timezone: "Asia/Manila" },
          { name: "Makati", timezone: "Asia/Manila" },
          { name: "General Santos", timezone: "Asia/Manila" },
          { name: "Bacolod", timezone: "Asia/Manila" },
        ],
      },
      {
        name: "Malaysia",
        cities: [
          { name: "Kuala Lumpur", timezone: "Asia/Kuala_Lumpur" },
          { name: "George Town (Penang)", timezone: "Asia/Kuala_Lumpur" },
          { name: "Ipoh", timezone: "Asia/Kuala_Lumpur" },
          { name: "Shah Alam", timezone: "Asia/Kuala_Lumpur" },
          { name: "Petaling Jaya", timezone: "Asia/Kuala_Lumpur" },
          { name: "Johor Bahru", timezone: "Asia/Kuala_Lumpur" },
          { name: "Subang Jaya", timezone: "Asia/Kuala_Lumpur" },
          { name: "Kota Kinabalu", timezone: "Asia/Kuching" },
          { name: "Kuching", timezone: "Asia/Kuching" },
          { name: "Malacca", timezone: "Asia/Kuala_Lumpur" },
        ],
      },
      {
        name: "Taiwan",
        cities: [
          { name: "Taipei", timezone: "Asia/Taipei" },
          { name: "New Taipei", timezone: "Asia/Taipei" },
          { name: "Taichung", timezone: "Asia/Taipei" },
          { name: "Kaohsiung", timezone: "Asia/Taipei" },
          { name: "Taoyuan", timezone: "Asia/Taipei" },
          { name: "Tainan", timezone: "Asia/Taipei" },
          { name: "Hsinchu", timezone: "Asia/Taipei" },
          { name: "Keelung", timezone: "Asia/Taipei" },
        ],
      },
      {
        name: "Hong Kong",
        cities: [
          { name: "Hong Kong Island", timezone: "Asia/Hong_Kong" },
          { name: "Kowloon", timezone: "Asia/Hong_Kong" },
          { name: "Sha Tin", timezone: "Asia/Hong_Kong" },
          { name: "Tsuen Wan", timezone: "Asia/Hong_Kong" },
        ],
      },
      {
        name: "Bangladesh",
        cities: [
          { name: "Dhaka", timezone: "Asia/Dhaka" },
          { name: "Chittagong", timezone: "Asia/Dhaka" },
          { name: "Sylhet", timezone: "Asia/Dhaka" },
          { name: "Rajshahi", timezone: "Asia/Dhaka" },
          { name: "Khulna", timezone: "Asia/Dhaka" },
          { name: "Gazipur", timezone: "Asia/Dhaka" },
        ],
      },
      {
        name: "Pakistan",
        cities: [
          { name: "Karachi", timezone: "Asia/Karachi" },
          { name: "Lahore", timezone: "Asia/Karachi" },
          { name: "Faisalabad", timezone: "Asia/Karachi" },
          { name: "Rawalpindi", timezone: "Asia/Karachi" },
          { name: "Islamabad", timezone: "Asia/Karachi" },
          { name: "Multan", timezone: "Asia/Karachi" },
          { name: "Hyderabad", timezone: "Asia/Karachi" },
          { name: "Peshawar", timezone: "Asia/Karachi" },
          { name: "Quetta", timezone: "Asia/Karachi" },
        ],
      },
      {
        name: "Sri Lanka",
        cities: [
          { name: "Colombo", timezone: "Asia/Colombo" },
          { name: "Dehiwala-Mount Lavinia", timezone: "Asia/Colombo" },
          { name: "Moratuwa", timezone: "Asia/Colombo" },
          { name: "Kandy", timezone: "Asia/Colombo" },
          { name: "Galle", timezone: "Asia/Colombo" },
        ],
      },
      {
        name: "Nepal",
        cities: [
          { name: "Kathmandu", timezone: "Asia/Kathmandu" },
          { name: "Pokhara", timezone: "Asia/Kathmandu" },
          { name: "Biratnagar", timezone: "Asia/Kathmandu" },
          { name: "Birgunj", timezone: "Asia/Kathmandu" },
        ],
      },
      {
        name: "Myanmar",
        cities: [
          { name: "Yangon", timezone: "Asia/Yangon" },
          { name: "Mandalay", timezone: "Asia/Yangon" },
          { name: "Naypyidaw", timezone: "Asia/Yangon" },
          { name: "Mawlamyine", timezone: "Asia/Yangon" },
        ],
      },
      {
        name: "Cambodia",
        cities: [
          { name: "Phnom Penh", timezone: "Asia/Phnom_Penh" },
          { name: "Siem Reap", timezone: "Asia/Phnom_Penh" },
          { name: "Sihanoukville", timezone: "Asia/Phnom_Penh" },
        ],
      },
      {
        name: "Mongolia",
        cities: [
          { name: "Ulaanbaatar", timezone: "Asia/Ulaanbaatar" },
          { name: "Erdenet", timezone: "Asia/Ulaanbaatar" },
        ],
      },
      {
        name: "Uzbekistan",
        cities: [
          { name: "Tashkent", timezone: "Asia/Tashkent" },
          { name: "Samarkand", timezone: "Asia/Samarkand" },
          { name: "Namangan", timezone: "Asia/Tashkent" },
          { name: "Andijan", timezone: "Asia/Tashkent" },
        ],
      },
    ],
  },
  {
    name: "Middle East",
    countries: [
      {
        name: "United Arab Emirates",
        cities: [
          { name: "Dubai", timezone: "Asia/Dubai" },
          { name: "Abu Dhabi", timezone: "Asia/Dubai" },
          { name: "Sharjah", timezone: "Asia/Dubai" },
          { name: "Al Ain", timezone: "Asia/Dubai" },
          { name: "Ajman", timezone: "Asia/Dubai" },
          { name: "Ras Al Khaimah", timezone: "Asia/Dubai" },
        ],
      },
      {
        name: "Israel",
        cities: [
          { name: "Jerusalem", timezone: "Asia/Jerusalem" },
          { name: "Tel Aviv", timezone: "Asia/Jerusalem" },
          { name: "Haifa", timezone: "Asia/Jerusalem" },
          { name: "Rishon LeZion", timezone: "Asia/Jerusalem" },
          { name: "Petah Tikva", timezone: "Asia/Jerusalem" },
          { name: "Ashdod", timezone: "Asia/Jerusalem" },
          { name: "Netanya", timezone: "Asia/Jerusalem" },
          { name: "Be'er Sheva", timezone: "Asia/Jerusalem" },
          { name: "Herzliya", timezone: "Asia/Jerusalem" },
          { name: "Eilat", timezone: "Asia/Jerusalem" },
        ],
      },
      {
        name: "Turkey",
        cities: [
          { name: "Istanbul", timezone: "Europe/Istanbul" },
          { name: "Ankara", timezone: "Europe/Istanbul" },
          { name: "Izmir", timezone: "Europe/Istanbul" },
          { name: "Bursa", timezone: "Europe/Istanbul" },
          { name: "Adana", timezone: "Europe/Istanbul" },
          { name: "Gaziantep", timezone: "Europe/Istanbul" },
          { name: "Antalya", timezone: "Europe/Istanbul" },
          { name: "Konya", timezone: "Europe/Istanbul" },
          { name: "Kayseri", timezone: "Europe/Istanbul" },
          { name: "Eskişehir", timezone: "Europe/Istanbul" },
          { name: "Mersin", timezone: "Europe/Istanbul" },
          { name: "Trabzon", timezone: "Europe/Istanbul" },
          { name: "Bodrum", timezone: "Europe/Istanbul" },
          { name: "Cappadocia", timezone: "Europe/Istanbul" },
        ],
      },
      {
        name: "Saudi Arabia",
        cities: [
          { name: "Riyadh", timezone: "Asia/Riyadh" },
          { name: "Jeddah", timezone: "Asia/Riyadh" },
          { name: "Mecca", timezone: "Asia/Riyadh" },
          { name: "Medina", timezone: "Asia/Riyadh" },
          { name: "Dammam", timezone: "Asia/Riyadh" },
          { name: "Khobar", timezone: "Asia/Riyadh" },
          { name: "Tabuk", timezone: "Asia/Riyadh" },
          { name: "Abha", timezone: "Asia/Riyadh" },
          { name: "NEOM", timezone: "Asia/Riyadh" },
        ],
      },
      {
        name: "Qatar",
        cities: [
          { name: "Doha", timezone: "Asia/Qatar" },
          { name: "Al Wakrah", timezone: "Asia/Qatar" },
          { name: "Al Khor", timezone: "Asia/Qatar" },
        ],
      },
      {
        name: "Kuwait",
        cities: [
          { name: "Kuwait City", timezone: "Asia/Kuwait" },
          { name: "Salmiya", timezone: "Asia/Kuwait" },
          { name: "Hawalli", timezone: "Asia/Kuwait" },
        ],
      },
      {
        name: "Bahrain",
        cities: [
          { name: "Manama", timezone: "Asia/Bahrain" },
          { name: "Riffa", timezone: "Asia/Bahrain" },
          { name: "Muharraq", timezone: "Asia/Bahrain" },
        ],
      },
      {
        name: "Oman",
        cities: [
          { name: "Muscat", timezone: "Asia/Muscat" },
          { name: "Sohar", timezone: "Asia/Muscat" },
          { name: "Salalah", timezone: "Asia/Muscat" },
          { name: "Nizwa", timezone: "Asia/Muscat" },
        ],
      },
      {
        name: "Jordan",
        cities: [
          { name: "Amman", timezone: "Asia/Amman" },
          { name: "Zarqa", timezone: "Asia/Amman" },
          { name: "Irbid", timezone: "Asia/Amman" },
          { name: "Aqaba", timezone: "Asia/Amman" },
        ],
      },
      {
        name: "Lebanon",
        cities: [
          { name: "Beirut", timezone: "Asia/Beirut" },
          { name: "Tripoli", timezone: "Asia/Beirut" },
          { name: "Sidon", timezone: "Asia/Beirut" },
        ],
      },
      {
        name: "Iraq",
        cities: [
          { name: "Baghdad", timezone: "Asia/Baghdad" },
          { name: "Basra", timezone: "Asia/Baghdad" },
          { name: "Mosul", timezone: "Asia/Baghdad" },
          { name: "Erbil", timezone: "Asia/Baghdad" },
          { name: "Sulaymaniyah", timezone: "Asia/Baghdad" },
          { name: "Kirkuk", timezone: "Asia/Baghdad" },
        ],
      },
      {
        name: "Iran",
        cities: [
          { name: "Tehran", timezone: "Asia/Tehran" },
          { name: "Mashhad", timezone: "Asia/Tehran" },
          { name: "Isfahan", timezone: "Asia/Tehran" },
          { name: "Karaj", timezone: "Asia/Tehran" },
          { name: "Tabriz", timezone: "Asia/Tehran" },
          { name: "Shiraz", timezone: "Asia/Tehran" },
          { name: "Ahvaz", timezone: "Asia/Tehran" },
          { name: "Qom", timezone: "Asia/Tehran" },
          { name: "Kermānshāh", timezone: "Asia/Tehran" },
          { name: "Rasht", timezone: "Asia/Tehran" },
        ],
      },
      {
        name: "Egypt",
        cities: [
          { name: "Cairo", timezone: "Africa/Cairo" },
          { name: "Alexandria", timezone: "Africa/Cairo" },
          { name: "Giza", timezone: "Africa/Cairo" },
          { name: "Shubra El-Kheima", timezone: "Africa/Cairo" },
          { name: "Port Said", timezone: "Africa/Cairo" },
          { name: "Suez", timezone: "Africa/Cairo" },
          { name: "Luxor", timezone: "Africa/Cairo" },
          { name: "Aswan", timezone: "Africa/Cairo" },
          { name: "Hurghada", timezone: "Africa/Cairo" },
          { name: "Sharm El-Sheikh", timezone: "Africa/Cairo" },
        ],
      },
    ],
  },
  {
    name: "Africa",
    countries: [
      {
        name: "Nigeria",
        cities: [
          { name: "Lagos", timezone: "Africa/Lagos" },
          { name: "Kano", timezone: "Africa/Lagos" },
          { name: "Ibadan", timezone: "Africa/Lagos" },
          { name: "Abuja", timezone: "Africa/Lagos" },
          { name: "Port Harcourt", timezone: "Africa/Lagos" },
          { name: "Benin City", timezone: "Africa/Lagos" },
          { name: "Maiduguri", timezone: "Africa/Lagos" },
          { name: "Zaria", timezone: "Africa/Lagos" },
          { name: "Aba", timezone: "Africa/Lagos" },
          { name: "Enugu", timezone: "Africa/Lagos" },
          { name: "Ilorin", timezone: "Africa/Lagos" },
          { name: "Onitsha", timezone: "Africa/Lagos" },
          { name: "Kaduna", timezone: "Africa/Lagos" },
          { name: "Warri", timezone: "Africa/Lagos" },
        ],
      },
      {
        name: "South Africa",
        cities: [
          { name: "Johannesburg", timezone: "Africa/Johannesburg" },
          { name: "Cape Town", timezone: "Africa/Johannesburg" },
          { name: "Durban", timezone: "Africa/Johannesburg" },
          { name: "Pretoria", timezone: "Africa/Johannesburg" },
          { name: "Port Elizabeth", timezone: "Africa/Johannesburg" },
          { name: "Bloemfontein", timezone: "Africa/Johannesburg" },
          { name: "Nelspruit", timezone: "Africa/Johannesburg" },
          { name: "Kimberley", timezone: "Africa/Johannesburg" },
          { name: "Pietermaritzburg", timezone: "Africa/Johannesburg" },
          { name: "East London", timezone: "Africa/Johannesburg" },
          { name: "Stellenbosch", timezone: "Africa/Johannesburg" },
        ],
      },
      {
        name: "Kenya",
        cities: [
          { name: "Nairobi", timezone: "Africa/Nairobi" },
          { name: "Mombasa", timezone: "Africa/Nairobi" },
          { name: "Kisumu", timezone: "Africa/Nairobi" },
          { name: "Nakuru", timezone: "Africa/Nairobi" },
          { name: "Eldoret", timezone: "Africa/Nairobi" },
          { name: "Malindi", timezone: "Africa/Nairobi" },
        ],
      },
      {
        name: "Ghana",
        cities: [
          { name: "Accra", timezone: "Africa/Accra" },
          { name: "Kumasi", timezone: "Africa/Accra" },
          { name: "Tamale", timezone: "Africa/Accra" },
          { name: "Sekondi-Takoradi", timezone: "Africa/Accra" },
          { name: "Cape Coast", timezone: "Africa/Accra" },
        ],
      },
      {
        name: "Ethiopia",
        cities: [
          { name: "Addis Ababa", timezone: "Africa/Addis_Ababa" },
          { name: "Dire Dawa", timezone: "Africa/Addis_Ababa" },
          { name: "Mek'ele", timezone: "Africa/Addis_Ababa" },
          { name: "Gondar", timezone: "Africa/Addis_Ababa" },
          { name: "Hawassa", timezone: "Africa/Addis_Ababa" },
        ],
      },
      {
        name: "Tanzania",
        cities: [
          { name: "Dar es Salaam", timezone: "Africa/Dar_es_Salaam" },
          { name: "Mwanza", timezone: "Africa/Dar_es_Salaam" },
          { name: "Arusha", timezone: "Africa/Dar_es_Salaam" },
          { name: "Dodoma", timezone: "Africa/Dar_es_Salaam" },
          { name: "Zanzibar City", timezone: "Africa/Dar_es_Salaam" },
        ],
      },
      {
        name: "Uganda",
        cities: [
          { name: "Kampala", timezone: "Africa/Kampala" },
          { name: "Gulu", timezone: "Africa/Kampala" },
          { name: "Mbarara", timezone: "Africa/Kampala" },
          { name: "Entebbe", timezone: "Africa/Kampala" },
        ],
      },
      {
        name: "Rwanda",
        cities: [
          { name: "Kigali", timezone: "Africa/Kigali" },
          { name: "Musanze", timezone: "Africa/Kigali" },
          { name: "Butare", timezone: "Africa/Kigali" },
        ],
      },
      {
        name: "Senegal",
        cities: [
          { name: "Dakar", timezone: "Africa/Dakar" },
          { name: "Thiès", timezone: "Africa/Dakar" },
          { name: "Touba", timezone: "Africa/Dakar" },
          { name: "Saint-Louis", timezone: "Africa/Dakar" },
        ],
      },
      {
        name: "Ivory Coast",
        cities: [
          { name: "Abidjan", timezone: "Africa/Abidjan" },
          { name: "Bouaké", timezone: "Africa/Abidjan" },
          { name: "Yamoussoukro", timezone: "Africa/Abidjan" },
          { name: "Daloa", timezone: "Africa/Abidjan" },
        ],
      },
      {
        name: "Cameroon",
        cities: [
          { name: "Douala", timezone: "Africa/Douala" },
          { name: "Yaoundé", timezone: "Africa/Douala" },
          { name: "Bamenda", timezone: "Africa/Douala" },
          { name: "Bafoussam", timezone: "Africa/Douala" },
        ],
      },
      {
        name: "Morocco",
        cities: [
          { name: "Casablanca", timezone: "Africa/Casablanca" },
          { name: "Fes", timezone: "Africa/Casablanca" },
          { name: "Tangier", timezone: "Africa/Casablanca" },
          { name: "Marrakech", timezone: "Africa/Casablanca" },
          { name: "Salé", timezone: "Africa/Casablanca" },
          { name: "Rabat", timezone: "Africa/Casablanca" },
          { name: "Meknès", timezone: "Africa/Casablanca" },
          { name: "Oujda", timezone: "Africa/Casablanca" },
          { name: "Agadir", timezone: "Africa/Casablanca" },
        ],
      },
      {
        name: "Tunisia",
        cities: [
          { name: "Tunis", timezone: "Africa/Tunis" },
          { name: "Sfax", timezone: "Africa/Tunis" },
          { name: "Sousse", timezone: "Africa/Tunis" },
          { name: "Ettadhamen", timezone: "Africa/Tunis" },
          { name: "Kairouan", timezone: "Africa/Tunis" },
          { name: "Monastir", timezone: "Africa/Tunis" },
        ],
      },
      {
        name: "Algeria",
        cities: [
          { name: "Algiers", timezone: "Africa/Algiers" },
          { name: "Oran", timezone: "Africa/Algiers" },
          { name: "Constantine", timezone: "Africa/Algiers" },
          { name: "Annaba", timezone: "Africa/Algiers" },
          { name: "Blida", timezone: "Africa/Algiers" },
          { name: "Batna", timezone: "Africa/Algiers" },
          { name: "Tlemcen", timezone: "Africa/Algiers" },
        ],
      },
      {
        name: "Zimbabwe",
        cities: [
          { name: "Harare", timezone: "Africa/Harare" },
          { name: "Bulawayo", timezone: "Africa/Harare" },
          { name: "Mutare", timezone: "Africa/Harare" },
          { name: "Gweru", timezone: "Africa/Harare" },
          { name: "Victoria Falls", timezone: "Africa/Harare" },
        ],
      },
      {
        name: "Angola",
        cities: [
          { name: "Luanda", timezone: "Africa/Luanda" },
          { name: "Huambo", timezone: "Africa/Luanda" },
          { name: "Lobito", timezone: "Africa/Luanda" },
          { name: "Benguela", timezone: "Africa/Luanda" },
        ],
      },
      {
        name: "Mozambique",
        cities: [
          { name: "Maputo", timezone: "Africa/Maputo" },
          { name: "Matola", timezone: "Africa/Maputo" },
          { name: "Nampula", timezone: "Africa/Maputo" },
          { name: "Beira", timezone: "Africa/Maputo" },
        ],
      },
      {
        name: "Zambia",
        cities: [
          { name: "Lusaka", timezone: "Africa/Lusaka" },
          { name: "Kitwe", timezone: "Africa/Lusaka" },
          { name: "Ndola", timezone: "Africa/Lusaka" },
          { name: "Livingstone", timezone: "Africa/Lusaka" },
        ],
      },
      {
        name: "Botswana",
        cities: [
          { name: "Gaborone", timezone: "Africa/Gaborone" },
          { name: "Francistown", timezone: "Africa/Gaborone" },
        ],
      },
      {
        name: "Namibia",
        cities: [
          { name: "Windhoek", timezone: "Africa/Windhoek" },
          { name: "Walvis Bay", timezone: "Africa/Windhoek" },
        ],
      },
      {
        name: "Sudan",
        cities: [
          { name: "Khartoum", timezone: "Africa/Khartoum" },
          { name: "Omdurman", timezone: "Africa/Khartoum" },
          { name: "Port Sudan", timezone: "Africa/Khartoum" },
        ],
      },
      {
        name: "Libya",
        cities: [
          { name: "Tripoli", timezone: "Africa/Tripoli" },
          { name: "Benghazi", timezone: "Africa/Tripoli" },
        ],
      },
    ],
  },
]

// Derived helpers
export const REGIONS = LOCATION_DATA.map((r) => r.name)

export function getCountriesForRegion(region: string): Country[] {
  return LOCATION_DATA.find((r) => r.name === region)?.countries ?? []
}

export function getCitiesForCountry(region: string, country: string): City[] {
  return getCountriesForRegion(region).find((c) => c.name === country)?.cities ?? []
}
