ALTER TABLE hacker_houses ADD COLUMN IF NOT EXISTS lat float8 DEFAULT NULL;
ALTER TABLE hacker_houses ADD COLUMN IF NOT EXISTS lng float8 DEFAULT NULL;

ALTER TABLE hack_spaces ADD COLUMN IF NOT EXISTS lat float8 DEFAULT NULL;
ALTER TABLE hack_spaces ADD COLUMN IF NOT EXISTS lng float8 DEFAULT NULL;
